import type { PlaybackMode, SequencePreset, StepResolution } from '../playlist-presets';

/** One note: [step, row index into rowNotes, length in steps, velocity 0–1]. */
export type SongNote = [number, number, number, number];

type Track = SequencePreset['tracks'][number];

/** A track as authored in a song file: a compact note list instead of a full grid. */
export interface SongTrack extends Omit<Track, 'grid' | 'ties'> {
  notes: SongNote[];
}

/**
 * A song as authored in src/app/data/songs/*.ts (generated by scripts/songs/build-song.py from Guitar Pro / MIDI
 * transcriptions). Stored as note lists so a full-band song stays small; expanded to the editor's grid format on load.
 */
export interface SongDef extends Omit<SequencePreset, 'tracks' | 'stepCount' | 'stepsPerBeat' | 'stepResolution' | 'load' | 'trackCount'> {
  stepCount: number;
  /** Grid steps per quarter note (4 = 16th notes, 12 = 16ths + triplets). `bpm` is the real tempo. */
  stepsPerBeat: number;
  stepResolution: StepResolution;
  /** Where the segment comes from, e.g. "Guitar Pro transcription, bars 1–16 (Intro)". */
  source?: string;
  tracks: SongTrack[];
}

/** Playlist entry for a built-in song: everything the song list shows, plus a loader for the notes. */
export interface SongMeta extends Omit<SongDef, 'tracks' | 'source' | 'swingPercentage' | 'humanize'> {
  trackCount: number;
  load: () => Promise<SongDef>;
}

/** Expands a compact song into the grid + ties format the sequencer edits and plays. */
export function expandSong(song: SongDef): SequencePreset {
  const { source: _source, ...rest } = song;
  return {
    ...rest,
    tracks: song.tracks.map(({ notes, ...track }) => {
      const grid = track.rowNotes.map(() => new Array<number>(song.stepCount).fill(0));
      const ties = track.rowNotes.map(() => new Array<boolean>(song.stepCount).fill(false));
      for (const [step, row, length, velocity] of notes) {
        if (step >= song.stepCount || !grid[row]) continue;
        grid[row][step] = velocity;
        for (let k = 1; k < length && step + k < song.stepCount; k++) ties[row][step + k] = true;
      }
      return { ...track, grid, ties };
    }),
  };
}

export type { PlaybackMode };
